// Predefine types
export const BARANGAYS_LOADING = 'BARANGAYS_LOADING';
export const BARANGAYS_SUCCESS = 'BARANGAYS_SUCCESS';
export const BARANGAYS_ERROR = 'BARANGAYS_ERROR';
export const BARANGAYS_CLEAR_RESPONSE = 'BARANGAYS_CLEAR_RESPONSE';

export const GET_ALL_BARANGAYS = 'GET_ALL_BARANGAYS';
export const GET_BARANGAY = 'GET_BARANGAY';
