// Predefine types
export const EMERGENCIES_LOADING = 'EMERGENCIES_LOADING';
export const EMERGENCIES_SUCCESS = 'EMERGENCIES_SUCCESS';
export const EMERGENCIES_ERROR = 'EMERGENCIES_ERROR';
export const EMERGENCIES_CLEAR_RESPONSE = 'EMERGENCIES_CLEAR_RESPONSE';

export const GET_ALL_EMERGENCIES = 'GET_ALL_EMERGENCIES';
export const GET_EMERGENCY = 'GET_EMERGENCY';
export const CLEAR_EMERGENCY = 'CLEAR_EMERGENCY';
