// Predefine types
export const REQUEST_BACKUPS_LOADING = 'REQUEST_BACKUPS_LOADING';
export const REQUEST_BACKUPS_SUCCESS = 'REQUEST_BACKUPS_SUCCESS';
export const REQUEST_BACKUPS_ERROR = 'REQUEST_BACKUPS_ERROR';
export const REQUEST_BACKUPS_CLEAR_RESPONSE = 'REQUEST_BACKUPS_CLEAR_RESPONSE';

export const GET_ALL_REQUEST_BACKUPS = 'GET_ALL_REQUEST_BACKUPS';
export const GET_REQUEST_BACKUP = 'GET_REQUEST_BACKUP';
